#!/bin/bash

yarn nearleyc src/gherkin.ne -o src/gherkin.umd.js || exit 1
yarn nearleyc src/tags-expression.ne -o src/tags-expression.umd.js || exit 1
yarn rollup -c rollup-gherkin.js || exit 1
yarn rollup -c rollup-tags-expression.js || exit 1
